apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-viewer-role
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "deployments", "services", "configmaps", "jobs", "nodes"]
  verbs: ["get", "list", "watch"]
