apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-engineer
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-viewer
  namespace: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-deployer
  namespace: prod
